Add back failure step

diff --git a/.github/workflows/deploy.staging.yml b/.github/workflows/deploy.staging.yml
--- a/.github/workflows/deploy.staging.yml
+++ b/.github/workflows/deploy.staging.yml
@@ -53,3 +53,9 @@ jobs:
           fi
 
           echo "Using commit SHA: $COMMIT_SHA"
+  on-failure:
+    
+    runs-on: ubuntu-latest
+    steps:
+      - run: echo "Deploy failed due to failed staging push CI"
+      - run: exit 1
