Fail required test

diff --git a/.github/workflows/pull_request_main.yml b/.github/workflows/pull_request_main.yml
--- a/.github/workflows/pull_request_main.yml
+++ b/.github/workflows/pull_request_main.yml
@@ -11,8 +11,8 @@ jobs:
     runs-on: ubuntu-latest
     steps:
       - run: |
-          echo "Dummy Required Check Passing"
-          exit 0
+          echo "Dummy Required Check Failing"
+          exit 1
   optional:
     name: Dummy Optional Check
     runs-on: ubuntu-latest
